#!/bin/bash
# python3 optimize_binning_bbWW.py --input-shapes /eos/user/d/daebi/bbWW/histograms/fwtest_15apr/Run3_2022EE/merged/ --file-name-pattern dnn_M0_Signal/dnn_M0_Signal.root --sig-name-pattern GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_{m} --output example_out/ --config ../../config/Datacards/x_hh_bbww_run3.yaml --mass-list 250,260,270,280,300,350,450,550,600,650,700,800 --channels eE,eMu,muMu --categories res1b_Zveto_MbbSR,res2b_Zveto_MbbSR --background-names TT,DY --important-backgrounds TT
# python3 optimize_binning_bbWW.py --input-shapes /eos/user/a/abolshov/HH_bbWW/histograms/limits_SL/Run3_2022/merged/ --file-name-pattern DoubleLep_DeepHME_mass/DoubleLep_DeepHME_mass.root --sig-name-pattern GluGluToRadion2L_{m} --output example_out/ --config ../../config/Datacards/x_hh_bbww_run3.yaml --mass-list 250,260,270,280,300,350,450,550,600,650,700,800 --channels eE,eMu,muMu --categories res1b_SR,res2b_SR --background-names TT,DY_LowMass,DY_HighMass --important-backgrounds TT

# Double Lep
# python3 optimize_binning_2D.py --input-shapes /eos/user/d/daebi/HH_bbWW/merged_hists/v2601a/Run3_2023BPix/ --file-name-pattern DL_DNN_m{m}_vs_HME/DL_DNN_m{m}_vs_HME.root --sig-name-pattern XtoHHto2B2W_2L_{m} --output 10Feb_DL/ --config ../../config/Datacards/x_hh_bbww_DL_run3.yaml --mass-list 300,400,500,550,600,650,700,800,900,1000 --channels eE,eMu,muMu --categories ZVeto_OS_Iso/res2b,ZVeto_OS_Iso/boosted,ZVeto_OS_Iso/recovery --background-names TT,DY,ST,VV --important-backgrounds TT,DY,ST,VV
python3 -i optimize_binning_2D.py --input-shapes /eos/user/d/daebi/HH_bbWW/merged_hists/v2601a/Run3_2023BPix/ --file-name-pattern DL_DNN_m{m}_vs_HME/DL_DNN_m{m}_vs_HME.root --sig-name-pattern XtoHHto2B2W_2L_{m} --output 11Feb_DL/ --config ../../config/Datacards/x_hh_bbww_DL_run3.yaml --mass-list 300,400,500,550,600,650,700,800,900,1000 --channels eE,eMu,muMu --categories ZVeto_OS_Iso/res2b,ZVeto_OS_Iso/boosted,ZVeto_OS_Iso/recovery --background-names TT,DY,ST,VV --important-backgrounds TT,DY

# Single Lep
# python3 optimize_binning_bbWW.py --input-shapes /eos/user/d/daebi/bbWW_development/merged_hists/6Dec25/Run3_2023BPix/ --file-name-pattern LinHMEDNN_SL_linear_hme_dnn_m{m}/LinHMEDNN_SL_linear_hme_dnn_m{m}.root --sig-name-pattern XtoHHto2B2W_1L_{m} --output 13Dec_SL/ --config ../../config/Datacards/x_hh_bbww_SL_run3.yaml --mass-list 300,400,500,550,600,650,700,800,900 --channels eE,eMu,muMu --categories ZVeto_OS_Iso/res2b,ZVeto_OS_Iso/boosted,ZVeto_OS_Iso/recovery --background-names TT,W,ST --important-backgrounds TT,W,ST
